-- mysql
CREATE TABLE users(
	id INT AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT NOW(),
	updated_at DATETIME NOT NULL DEFAULT NOW()
	PRIMARY KEY(id)
);

-- sqlite
-- DATE('NOW')
CREATE TABLE users(
	id INT AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at VARCHAR(255) NOT NULL,
	updated_at VARCHAR(255) NOT NULL
	PRIMARY KEY(id)
);

